### ISSUE TITLE
Reservasi Walkin Tidak Refresh

### ISSUE THREAD

**Issue by muchsinabdillah** [muchsinabdillah/ESIRYARSI-V2#25]
Setelah berhasil buat reservasi, halaman tidak refresh ke List Reservasi.

**Comment by daisnurfaizi** [comment]
meambahkan    setTimeout(function() { window.location.replace(base_url+"/ESIRYARSI/public/aReservasiPasienWalkin"); }, 3000);
sebelum redirect ke list
